ctrl_interface_group=networkmanager
ctrl_interface=DIR=/run/wpa_supplicant
update_config=1
ap_scan=1

network={
  proto=WPA2
  pairwise=CCMP
  key_mgmt=WPA-PSK
  priority=1
	ssid="Redmi8"
  scan_ssid=1
  psk="huesosi26"
}

network={
  key_mgmt=NONE
  priority=2
  ssid="Moscow_WiFi_Free"
  scan_ssid=1
}

network={
  proto=WPA2
  pairwise=CCMP
  key_mgmt=WPA-PSK
	ssid="INTERNET_WIRLESS_5G"
  scan_ssid=1
	psk=1646d1c80375a8a2eb623696670126f297ecbc670838d33e173cd6feac02426e
}

network={
  ssid="bmstu_wifi"
  key_mgmt=WPA-EAP
  eap=PEAP
  identity="byui24l290"
  password="pRd9fOddS1kNK"
  phase1="peaplabel=0"
  phase2="auth=MSCHAPV2"
  scan_ssid=1
}
